# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: monorail
networks:
  - id: 10143
    start_block: 18155246
    end_block: 18155246
    contracts:
      - name: Aggregate
        address:
          - 0xC995498c22a012353FAE7eCC701810D673E25794
        handler: src/EventHandlers.ts
        events:
          - event: Aggregation(address indexed tokenAddress, address indexed outTokenAddress, uint256 amount, uint256 destinationAmount, uint256 feeAmount)
            field_selection:
              transaction_fields:
                - "hash"
                - "from"
                - "input"
                - "value"
                - "gas"
                - "gasPrice"
      - name: AggregateV3
        address:
          - 0x84345F7bBC538e2C3D384800A2FF01DB4844822e
          - 0x7C8f8076B3E59F00000AEa4E4bF197d22a5e4F6D
        handler: src/EventHandlersV3.ts
        events:
          - event: Aggregated(address indexed sender, address indexed tokenIn, address indexed tokenOut, uint256 amount, uint256 destinationAmount, uint256 feeAmount)
            field_selection:
              transaction_fields:
                - "hash"
                - "from"
                - "input"
                - "value"
                - "gas"
                - "gasPrice"
          - event: AggregatedTrade(address indexed router, address indexed tokenIn, address indexed tokenOut, uint256 amount)
            field_selection:
              transaction_fields:
                - "hash"
                - "from"
                - "input"
                - "value"
                - "gas"
                - "gasPrice"
